# Generated by Django 3.2.3 on 2021-06-13 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num', models.CharField(default='K100', max_length=10, verbose_name='车次号')),
                ('name', models.CharField(default='', max_length=30, verbose_name='出发站-到达站')),
                ('time', models.CharField(default='', max_length=20, verbose_name='出发时间')),
                ('seats', models.IntegerField(default=0, verbose_name='剩余座位')),
            ],
            options={
                'verbose_name': '车票信息',
                'verbose_name_plural': '车票信息',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=10, verbose_name='乘客名称')),
                ('train', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='booking.train')),
            ],
            options={
                'verbose_name': '乘客信息',
                'verbose_name_plural': '乘客信息',
            },
        ),
    ]
